### ISSUE TITLE
Add IScreen interface

### ISSUE THREAD

**Issue by RGushchin97** [aquality-automation/aquality-appium-mobile-java#16]
When application has to be tested on both mobile platforms iOS and Android it is convenient to create interfaces for screens for using them without depending on platform.

**Comment by mialeska** [comment]
I would also vote for some ScreenFactory implementation inside of the library, for the same case.
@DmitryBogatko please define a priority for this issue

**Comment by pavelanihimovsky** [comment]
Add also ScreenFactory
