### ISSUE TITLE
Hide credentials in remoteConnectionUrl

### ISSUE THREAD

**Issue by 204alex** [aquality-automation/aquality-appium-mobile-java#26]
In case of browserstack we have to use credentials in remoteConnectionUrl. Would be great to hide them in logs. See attachments

![issue1](https://user-images.githubusercontent.com/70561560/114739784-dcf6b680-9d51-11eb-8077-6e2452ff42c0.PNG)

![issue2](https://user-images.githubusercontent.com/70561560/114739797-dff1a700-9d51-11eb-9bb5-6bbf3b0b642f.PNG)

**Comment by mialeska** [comment]
@204alex I believe setting credentials in URL is legacy. There is an option to set browserstack credentials in capabilities. Capabilities could be overridden with environment variables. You will have in settings.json smth like that:
`
  
  "platformName": "ios",
  "isRemote": true,
  "remoteConnectionUrl": "http://hub-cloud.browserstack.com/wd/hub",
  "screensLocation": "screens",
  "driverSettings": {
    "ios": {
      "deviceKey": "BrowserStack_iOS",
      "capabilities": {
        "app": "bs://yourhash",
        "platformName": "iOS",
        "bundleId": "yourBundleId",
        "browserstack.user": null,
        "browserstack.key": null,
        "browserstack.idleTimeout": "320",
        "project": "yourProject-iOS",
        "build": "1.0 (12345) on May 6, 2021",
        "imageMatchThreshold": 0.3,
        "fixImageTemplateScale": true
      }
    }
      `
      
     Then you will set environment variables in you pipeline before the test execution      
     "driverSettings.ios.capabilities.browserstack.user" to your user 
     and 
     "driverSettings.ios.capabilities.browserstack.key" to your key
